//App Language Dictionaries
import enUS from './Language/en/US.json'
import esUS from './Language/es/US.json'
import esMX from './Language/es/MX.json'
import esES from './Language/es/ES.json'
import deDE from './Language/de/DE.json'
import frFR from './Language/fr/FR.json'
import frGF from './Language/fr/GF.json'
import hiIN from './Language/hi/IN.json'
import nlBE from './Language/nl/BE.json'
import nlNL from './Language/nl/NL.json'
import ruRU from './Language/ru/RU.json'
import zhMC from './Language/zh/MC.json'
import zhHK from './Language/zh/HK.json'
import zhTW from './Language/zh/TW.json'
import zhCDO from './Language/zh/CDO.json'
import zhCJY from './Language/zh/CJY.json'
import zhCMN from './Language/zh/CMN.json'
import zhCNP from './Language/zh/CNP.json'
import zhCSH from './Language/zh/CSH.json'
import zhCPX from './Language/zh/CPX.json'
import zhCSP from './Language/zh/CSP.json'
import zhMIN from './Language/zh/MIN.json'
import zhGAN from './Language/zh/GAN.json'
import zhHAK from './Language/zh/HAK.json'
import zhHSN from './Language/zh/HSN.json'
import zhLZH from './Language/zh/LZH.json'
import zhMNP from './Language/zh/MNP.json'
import zhNAN from './Language/zh/NAN.json'
import zhWUU from './Language/zh/WUU.json'
import zhYUE from './Language/zh/YUE.json'

//Application Language Dictionaries stored into single object.
export const LANGUAGE_DICTIONARIES = {
    en: { US: enUS },
    es: { US: esUS, MX: esMX, ES: esES },
    de: { DE: deDE },
    fr: { FR: frFR, GF: frGF },
    hi: { IN: hiIN },
    nl: { BE: nlBE, NL: nlNL },
    ru: { RU: ruRU },
    zh: {
        MC: zhMC,
        HK: zhHK,
        TW: zhTW,
        CDO: zhCDO,
        CJY: zhCJY,
        CMN: zhCMN,
        CNP: zhCNP,
        CPX: zhCPX,
        CSP: zhCSP,
        CSH: zhCSH,
        MIN: zhMIN,
        GAN: zhGAN,
        HAK: zhHAK,
        HSN: zhHSN,
        LZH: zhLZH,
        MNP: zhMNP,
        NAN: zhNAN,
        WUU: zhWUU,
        YUE: zhYUE
    }
}

export const CLIENT_ADDRESS = `${process.env.NEXT_PUBLIC_META_CLIENT_SERVER_URL}`
export const CLIENT_ENVIRONMENT = `${process.env.NEXT_PUBLIC_META_ENVIRONMENT}`
export const MAIL_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_MAIL_SERVER_URL}/api`
export const USERS_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_USER_SERVER_URL}/api`
export const USERS_SERVER_COOKIE_NAME = process.env.NEXT_PUBLIC_USERS_SERVER_COOKIE_NAME

export const CHAT_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_CHAT_SERVER_URL}/api`
export const CHAT_SERVER_ADDRESS_WSPROTOCOL = `${process.env.NEXT_PUBLIC_META_CHAT_SOCKET_URL}/api`
export const CHAT_SERVER_UNIVERSE_NAME = `${process.env.NEXT_PUBLIC_META_CHAT_UNIVERSE_NAME}`
export const USERS_CACHE_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_USERS_CACHE_SERVER_URL}`

export const USERS_PROFILE_CACHE_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_USERS_PROFILE_CACHE_SERVER_URL}`

export const APPLICATION_NEWS_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_APPLICATION_NEWS_SERVER_URL}`

export const APPLICATION_TWITCH_CLIENT_ID = `${process.env.NEXT_PUBLIC_META_TWITCH_CLIENT_ID}`
export const APPLICATION_TWITCH_LOGIN_REDIRECT_URI = `${process.env.NEXT_PUBLIC_META_TWITCH_CLIENT_LOGIN_REDIRECT_URI}`
export const USERS_TWITCH_CACHE_SERVER_ADDRESS = `${process.env.NEXT_PUBLIC_META_USERS_TWITCH_CACHE_SERVER_URL}`

export const USERS_FRIENDS_LIST_CACHE_SERVER = `${process.env.NEXT_PUBLIC_META_USERS_FRIENDS_LIST_CACHE_SERVER}`
export const USERS_BLOCKED_LIST_CACHE_SERVER = `${process.env.NEXT_PUBLIC_META_USERS_BLOCKED_LIST_CACHE_SERVER}`
export const USERS_REPORTED_LIST_CACHE_SERVER = `${process.env.NEXT_PUBLIC_META_USERS_REPORTED_LIST_CACHE_SERVER}`

export const APPLICATION_DISCORD_CLIENT_ID = `${process.env.NEXT_PUBLIC_META_DISCORD_CLIENT_ID}`
export const APPLICATION_DISCORD_REDIRECT_URI = `${process.env.NEXT_PUBLIC_META_DISCORD_CLIENT_REDIRECT_URI}`

export const ENCRYPTION_KEY = process.env.NEXT_PUBLIC_ENCRYPTION_KEY
export const ENCRYPTION_TYPE = process.env.NEXT_PUBLIC_ENCRYPTION_TYPE
export const ENCRYPTION_FORMAT = process.env.NEXT_PUBLIC_ENCRYPTION_FORMAT
export const ENCRYPTION_BASE = process.env.NEXT_PUBLIC_ENCRYPTION_BASE
export const ENCRYPTION_IV = process.env.NEXT_PUBLIC_ENCRYPTION_IV
export const JWT_ISSUER_KEY = process.env.NEXT_PUBLIC_JWT_ISSUER_KEY
export const JWT_CLIENT_KEY = process.env.NEXT_PUBLIC_JWT_CLIENT_KEY

export const META_TAG_CREATOR = process.env.NEXT_PUBLIC_META_TAG_CREATOR
export const META_TAG_AUTHOR = process.env.NEXT_PUBLIC_META_TAG_AUTHOR

//States
export const HTML_State = "HTML_State"
export const CSS_Structure_State = "CSS_Structure_State"
export const CSS_Design_State = "CSS_Design_State"
export const ReactBootstrap_State = "ReactBootstrap_State"
export const Host_Error_State = "Host_Error_State"
export const Network_Error_State = "Network_Error_State"
export const Twitch_API_State = "Twitch_API_State"
export const Discord_API_State = "Discord_API_State"

export const Application_Settings_State = "Application_Settings_State"
export const Application_Profile_Viewer_State = "Application_Profile_Viewer_State"
export const Application_WebSocket_State = "Application_WebSocket_State"
export const Application_Notification_State = "Application_Notification_State"
export const Application_Language_State = "Application_Language_State"

export const End_User_Account_State = "End_User_Account_State"
export const End_User_Profile_State = "End_User_Profile_State"
export const Application_Community_State = "Application_Community_State"
export const End_User_Discord_Account_State = "End_User_Discord_Account_State"
export const End_User_Twitch_Account_State = "End_User_Twitch_Account_State"

//Reducer Actions
export const UPDATE_APPLICATION_STATE = "UPDATE_APPLICATION_STATE"
export const NULL_APPLICATION_STATE = "NULL_APPLICATION_STATE"

export const UPDATE_APPLICATION_SETTINGS_NAV_SHOW = "UPDATE_APPLICATION_SETTINGS_NAV_SHOW"
export const NULL_APPLICATION_SETTINGS_NAV_SHOW = "NULL_APPLICATION_SETTINGS_NAV_SHOW"

export const UPDATE_APPLICATION_MOBILE_STATE = "UPDATE_APPLICATION_MOBILE_STATE"

export const UPDATE_APPLICATION_LANGUAGE_CURRENT_VALUE = "UPDATE_APPLICATION_LANGUAGE_CURRENT_VALUE"
export const DEFAULT_APPLICATION_LANGUAGE_CURRENT_VALUE = "DEFAULT_APPLICATION_LANGUAGE_CURRENT_VALUE"

export const UPDATE_APPLICATION_SETTINGS_MAX_BOOTSTRAP_GRID_COLUMNS = "UPDATE_APPLICATION_SETTINGS_MAX_BOOTSTRAP_GRID_COLUMNS"
export const DEFAULT_APPLICATION_SETTINGS_MAX_BOOTSTRAP_GRID_COLUMNS = "DEFAULT_APPLICATION_SETTINGS_MAX_BOOTSTRAP_GRID_COLUMNS"

export const UPDATE_END_USER_ACCOUNT_ONLINE_STATUS = "UPDATE_END_USER_ACCOUNT_ONLINE_STATUS"
export const NULL_END_USER_ACCOUNT_ONLINE_STATUS = "NULL_END_USER_ACCOUNT_ONLINE_STATUS"

export const UPDATE_APPLICATION_WEBSOCKET_STATE = "UPDATE_APPLICATION_WEBSOCKET_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATIONS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATIONS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_PERMISSIONS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_PERMISSIONS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_USAGE_PERMISSIONS_STATE = "UPDATE_APPLICATION_WEBSOCKET_USAGE_PERMISSIONS_STATE"

export const NULL_APPLICATION_WEBSOCKET_STATE = "NULL_APPLICATION_WEBSOCKET_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATIONS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATIONS_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_PERMISSIONS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_PERMISSIONS_STATE"
export const NULL_APPLICATION_WEBSOCKET_USAGE_PERMISSIONS_STATE = "NULL_APPLICATION_WEBSOCKET_USAGE_PERMISSIONS_STATE"

export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_REQUESTS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_REQUESTS_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_BLOCKS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_BLOCKS_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_APPROVALS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_SENT_APPROVALS_STATE"

export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_REQUESTS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_REQUESTS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_BLOCKS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_BLOCKS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_APPROVALS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_SENT_APPROVALS_STATE"

export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_REQUESTS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_REQUESTS_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_BLOCKS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_BLOCKS_STATE"
export const NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_APPROVALS_STATE = "NULL_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_APPROVALS_STATE"

export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_REQUESTS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_REQUESTS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_BLOCKS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_BLOCKS_STATE"
export const UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_APPROVALS_STATE = "UPDATE_APPLICATION_WEBSOCKET_CONVERSATION_RECEIVED_APPROVALS_STATE"

export const UPDATE_APPLICATION_PROFILE_VIEWER_STATE = "UPDATE_APPLICATION_PROFILE_VIEWER_STATE"
export const NULL_APPLICATION_PROFILE_VIEWER_STATE = "NULL_APPLICATION_PROFILE_VIEWER_STATE"

export const UPDATE_APPLICATION_SETTINGS_STATE = "UPDATE_APPLICATION_SETTINGS_STATE"
export const DEFAULT_APPLICATION_SETTINGS_STATE = "DEFAULT_APPLICATION_SETTINGS_STATE"

export const READ_APPLICATION_USERS = "READ_APPLICATION_USERS"

export const UPDATE_REACTBOOTSTRAP_STATE = "UPDATE_REACTBOOTSTRAP_STATE"
export const NULL_REACTBOOTSTRAP_STATE = "NULL_REACTBOOTSTRAP_STATE"

export const UPDATE_CSS_STRUCTURE_STATE = "UPDATE_CSS_STRUCTURE_STATE"
export const NULL_CSS_STRUCTURE_STATE = "NULL_CSS_STRUCTURE_STATE"

export const UPDATE_HTML_STATE = "UPDATE_HTML_STATE"
export const NULL_HTML_STATE = "NULL_HTML_STATE"

export const UPDATE_HOST_ERROR_STATE = "UPDATE_HOST_ERROR_STATE"
export const DEFAULT_HOST_ERROR_STATE = "DEFAULT_HOST_ERROR_STATE"

export const UPDATE_NETWORK_ERROR_STATE = "UPDATE_NETWORK_ERROR_STATE"
export const DEFAULT_NETWORK_ERROR_STATE = "DEFAULT_NETWORK_ERROR_STATE"

export const UPDATE_END_USER_ACCOUNT_STATE = "UPDATE_END_USER_ACCOUNT_STATE"
export const NULL_END_USER_ACCOUNT_STATE = "NULL_END_USER_ACCOUNT_STATE"

export const UPDATE_END_USER_DISCORD_ACCOUNT_STATE = "UPDATE_END_USER_DISCORD_ACCOUNT_STATE"
export const NULL_END_USER_DISCORD_ACCOUNT_STATE = "NULL_END_USER_DISCORD_ACCOUNT_STATE"

export const UPDATE_END_USER_TWITCH_ACCOUNT_STATE = "UPDATE_END_USER_TWITCH_ACCOUNT_STATE"
export const NULL_END_USER_TWITCH_ACCOUNT_STATE = "NULL_END_USER_TWITCH_ACCOUNT_STATE"

export const UPDATE_APPLICATION_COMMUNITY_STATE = "UPDATE_APPLICATION_COMMUNITY_STATE"
export const NULL_APPLICATION_COMMUNITY_STATE = "NULL_APPLICATION_COMMUNITY_STATE"

export const UPDATE_END_USER_PROFILE_ACCOUNT_STATE = "UPDATE_END_USER_PROFILE_ACCOUNT_STATE"
export const NULL_END_USER_PROFILE_ACCOUNT_STATE = "NULL_END_USER_PROFILE_ACCOUNT_STATE"

export const UPDATE_END_USER_PROFILE_STATE = "UPDATE_END_USER_PROFILE_STATE"
export const NULL_END_USER_PROFILE_STATE = "NULL_END_USER_PROFILE_STATE"

export const UPDATE_APPLICATION_NOTIFICATION_STATE = "UPDATE_APPLICATION_NOTIFICATION_STATE"
export const NULL_APPLICATION_NOTIFICATION_STATE = "NULL_APPLICATION_NOTIFICATION_STATE"

export const UPDATE_DISCORD_API_STATE = "UPDATE_DISCORD_API_STATE"
export const NULL_DISCORD_API_STATE = "NULL_DISCORD_API_STATE"

export const UPDATE_TWITCH_API_STATE = "UPDATE_TWITCH_API_STATE"
export const NULL_TWITCH_API_STATE = "NULL_TWITCH_API_STATE"

export const UPDATE_GOOGLE_API_STATE = "UPDATE_GOOGLE_API_STATE"
export const NULL_GOOGLE_API_STATE = "NULL_GOOGLE_API_STATE"

export const UPDATE_FACEBOOK_API_STATE = "UPDATE_FACEBOOK_API_STATE"
export const NULL_FACEBOOK_API_STATE = "NULL_FACEBOOK_API_STATE"

export const UPDATE_APPLICATION_SETTINGS_DATE = "UPDATE_APPLICATION_SETTINGS_DATE"
export const NULL_APPLICATION_DATE_SETTING_STATE = "NULL_APPLICATION_DATE_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_GLOBAL_TIME = "UPDATE_APPLICATION_SETTINGS_GLOBAL_TIME"
export const NULL_APPLICATION_GLOBAL_TIME_SETTING_STATE = "NULL_APPLICATION_GLOBAL_TIME_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_LOCAL_TIME = "UPDATE_APPLICATION_SETTINGS_LOCAL_TIME"
export const NULL_APPLICATION_LOCAL_TIME_SETTING_STATE = "NULL_APPLICATION_LOCAL_TIME_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_FLAG = "UPDATE_APPLICATION_SETTINGS_FLAG"
export const NULL_APPLICATION_FLAG_SETTING_STATE = "NULL_APPLICATION_FLAG_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_THEME = "UPDATE_APPLICATION_SETTINGS_THEME"
export const NULL_APPLICATION_THEME_SETTING_STATE = "NULL_APPLICATION_THEME_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_TEXT_ALIGNMENT = "UPDATE_APPLICATION_SETTINGS_TEXT_ALIGNMENT"
export const NULL_APPLICATION_TEXT_ALIGNMENT_SETTING_STATE = "NULL_APPLICATION_TEXT_ALIGNMENT_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_NAV_LOCK = "UPDATE_APPLICATION_SETTINGS_NAV_LOCK"
export const NULL_APPLICATION_NAV_LOCK_SETTING_STATE = "NULL_APPLICATION_NAV_LOCK_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_ALIGNMENT = "UPDATE_APPLICATION_SETTINGS_ALIGNMENT"
export const NULL_APPLICATION_ALIGNMENT_SETTING_STATE = "NULL_APPLICATION_ALIGNMENT_SETTING_STATE"

export const UPDATE_APPLICATION_SETTINGS_LOCATION = "UPDATE_APPLICATION_SETTINGS_LOCATION"
export const NULL_APPLICATION_LOCATION_SETTING_STATE = "NULL_APPLICATION_LOCATION_SETTING_STATE"

export const UPDATE_END_USER_PROFILE_ACCOUNT_FIRST_NAME = "UPDATE_END_USER_PROFILE_ACCOUNT_FIRST_NAME"
export const UPDATE_END_USER_PROFILE_ACCOUNT_LAST_NAME = "UPDATE_END_USER_PROFILE_ACCOUNT_LAST_NAME"
export const UPDATE_END_USER_PROFILE_ACCOUNT_MIDDLE_NAME = "UPDATE_END_USER_PROFILE_ACCOUNT_MIDDLE_NAME"
export const UPDATE_END_USER_PROFILE_ACCOUNT_MAIDEN_NAME = "UPDATE_END_USER_PROFILE_ACCOUNT_MAIDEN_NAME"
export const UPDATE_END_USER_PROFILE_ACCOUNT_GENDER = "UPDATE_END_USER_PROFILE_ACCOUNT_GENDER"
export const UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_MONTH = "UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_MONTH"
export const UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_DAY = "UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_DAY"
export const UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_YEAR = "UPDATE_END_USER_PROFILE_ACCOUNT_BIRTH_YEAR"
export const UPDATE_END_USER_PROFILE_ACCOUNT_ETHNICITY = "UPDATE_END_USER_PROFILE_ACCOUNT_ETHNICITY"
export const UPDATE_END_USER_ACCOUNT_CUSTOM_LABEL = "UPDATE_END_USER_ACCOUNT_CUSTOM_LABEL"
export const UPDATE_END_USER_ACCOUNT_EMAIL_ADDRESS = "UPDATE_END_USER_ACCOUNT_EMAIL_ADDRESS"
export const UPDATE_END_USER_ACCOUNT_LOGIN_TYPE = "UPDATE_END_USER_ACCOUNT_LOGIN_TYPE"
export const UPDATE_END_USER_ACCOUNT_ACCOUNT_TYPE = "UPDATE_END_USER_ACCOUNT_ACCOUNT_TYPE"
export const UPDATE_END_USER_ACCOUNT_NAME = "UPDATE_END_USER_ACCOUNT_NAME"
export const UPDATE_END_USER_ACCOUNT_AVATAR_URL_PATH = "UPDATE_END_USER_ACCOUNT_AVATAR_URL_PATH"
export const UPDATE_END_USER_ACCOUNT_AVATAR_TITLE = "UPDATE_END_USER_ACCOUNT_AVATAR_TITLE"
export const UPDATE_END_USER_ACCOUNT_GROUPS = "UPDATE_END_USER_ACCOUNT_GROUPS"
export const UPDATE_END_USER_ACCOUNT_ROLES = "UPDATE_END_USER_ACCOUNT_ROLES"
export const UPDATE_END_USER_ACCOUNT_AVATAR = "UPDATE_END_USER_ACCOUNT_AVATAR"

export const UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_FONT = "UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_FONT"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_BACKGROUND_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_BACKGROUND_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_FONT_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_HEADER_FONT_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_FONT = "UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_FONT"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_BACKGROUND_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_BACKGROUND_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_FONT_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_BODY_FONT_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_FONT = "UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_FONT"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_BACKGROUND_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_BACKGROUND_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_FONT_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_FOOTER_FONT_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_BACKGROUND_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_BACKGROUND_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_FONT_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_FONT_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_FONT = "UPDATE_CSS_CUSTOM_DESIGN_NAVIGATION_MENU_FONT"
export const UPDATE_CSS_CUSTOM_DESIGN_BUTTON_BACKGROUND_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_BUTTON_BACKGROUND_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_BUTTON_FONT_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_BUTTON_FONT_COLOR"
export const UPDATE_CSS_CUSTOM_DESIGN_BUTTON_FONT = "UPDATE_CSS_CUSTOM_DESIGN_BUTTON_FONT"
export const UPDATE_CSS_CUSTOM_DESIGN_CARD_BORDER_COLOR = "UPDATE_CSS_CUSTOM_DESIGN_CARD_BORDER_COLOR"
export const DEFAULT_CSS_CUSTOM_DESIGN_STATE = "DEFAULT_CSS_CUSTOM_DESIGN_STATE"
export const UPDATE_CSS_CUSTOM_DESIGN_STATE = "UPDATE_CSS_CUSTOM_DESIGN_STATE"

export const UPDATE_APPLICATION_NEWS_FEED_STATE = "UPDATE_APPLICATION_NEWS_FEED_STATE"
export const NULL_APPLICATION_NEWS_FEED_STATE = "NULL_APPLICATION_NEWS_FEED_STATE"

export const UPDATE_END_USER_TWITCH_STREAM_STATE = "UPDATE_END_USER_TWITCH_STREAM_STATE"
export const NULL_END_USER_TWITCH_STREAM_STATE = "NULL_END_USER_TWITCH_STREAM_STATE"

export const UPDATE_END_USER_TWITCH_FOLLOWS_STATE = "UPDATE_END_USER_TWITCH_FOLLOWS_STATE"
export const NULL_END_USER_TWITCH_FOLLOWS_STATE = "NULL_END_USER_TWITCH_FOLLOWS_STATE"

export const UPDATE_END_USER_TWITCH_FOLLOWERS_STATE = "UPDATE_END_USER_TWITCH_FOLLOWERS_STATE"
export const NULL_END_USER_TWITCH_FOLLOWERS_STATE = "NULL_END_USER_TWITCH_FOLLOWERS_STATE"

export const UPDATE_END_USER_TWITCH_CHANNEL_STATE = "UPDATE_END_USER_TWITCH_CHANNEL_STATE"
export const NULL_END_USER_TWITCH_CHANNEL_STATE = "NULL_END_USER_TWITCH_CHANNEL_STATE"

export const UPDATE_END_USER_TWITCH_VIDEOS_STATE = "UPDATE_END_USER_TWITCH_VIDEOS_STATE"
export const NULL_END_USER_TWITCH_VIDEOS_STATE = "NULL_END_USER_TWITCH_VIDEOS_STATE"

export const UPDATE_END_USER_TWITCH_CLIPS_STATE = "UPDATE_END_USER_TWITCH_CLIPS_STATE"
export const NULL_END_USER_TWITCH_CLIPS_STATE = "NULL_END_USER_TWITCH_CLIPS_STATE"

export const UPDATE_APPLICATION_PROGRESS_BAR_STATUS_VALUE = "UPDATE_APPLICATION_PROGRESS_BAR_STATUS_VALUE"

export const UPDATE_END_USER_FRIENDS_STATE = "UPDATE_END_USER_FRIENDS_STATE"
export const NULL_END_USER_FRIENDS_STATE = "NULL_END_USER_FRIENDS_STATE"

export const UPDATE_END_USER_FRIENDS_PERMISSION_STATE = "UPDATE_END_USER_FRIENDS_PERMISSION_STATE"
export const NULL_END_USER_FRIENDS_PERMISSION_STATE = "NULL_END_USER_FRIENDS_PERMISSION_STATE"

export const UPDATE_END_USER_FRIENDS_SENT_PERMISSION_STATE = "UPDATE_END_USER_FRIENDS_SENT_PERMISSION_STATE"
export const UPDATE_END_USER_FRIENDS_RECEIVED_PERMISSION_STATE = "UPDATE_END_USER_FRIENDS_RECEIVED_PERMISSION_STATE"

export const UPDATE_END_USER_FRIENDS_APPROVED_PERMISSION_STATE = "UPDATE_END_USER_FRIENDS_APPROVED_PERMISSION_STATE"
export const NULL_END_USER_FRIENDS_APPROVED_PERMISSION_STATE = "NULL_END_USER_FRIENDS_APPROVED_PERMISSION_STATE"

export const UPDATE_END_USER_REPORTED_USER_STATE = "UPDATE_END_USER_REPORTED_USER_STATE"
export const NULL_END_USER_REPORTED_USER_STATE = "NULL_END_USER_REPORTED_USER_STATE"